
name: Docker

on:
    workflow_call:
    
jobs:
    docker:
        name: Docker em S.O. ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        environment: Teste_ci
        strategy:
            matrix:
                os: [ 'ubuntu-latest' ]
        
        steps:
        - uses: actions/checkout@v3

        - name: Set up Docker Build
          uses: docker/setup-buildx-action@v3.8.0

        - name: Download a Build Artifact
          uses: download-artifact@v4.1.8
          with:
              name: programa
              path: devops/ci/projeto-go-testes-main/  

        - name: Docker Login
          uses: docker/login-action@v3.3.0
          with:
            username: albertrml
            password: ${{ secrets.DOCKER_PASSWORD }}
          
