# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Workflow curso de ci

on:
    push:
        branches: [ '*' ]
    pull_request:
        branches: [ '*' ]
    
jobs:
    test:
        name: Teste com Go ${{ matrix.go_version }} em S.O. ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        env:
            HOST: localhost
            PORT: 5432
            USER: root
            PASSWORD: root
            DBNAME: root
        strategy:
            matrix:
                go_version: [ '>=1.18', '1.18', '1.17' ]
                os: [ 'ubuntu-latest' ]
        
        steps:
        - uses: actions/checkout@v3

        - name: Set up Go
          uses: actions/setup-go@v3
          with:
            go-version: ${{ matrix.go_version }}

        - name: Install Docker Compose
          run: |
            sudo apt-get update
            sudo apt-get install -y docker-compose

        - name: Build-DB
          run: docker-compose build
          working-directory: devops/ci/projeto-go-testes-main

        - name: Create-DB
          run: docker-compose up -d
          working-directory: devops/ci/projeto-go-testes-main

        - name: Test
          run: go test -v main_test.go
          working-directory: devops/ci/projeto-go-testes-main

    build:
        needs: test
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ 'ubuntu-latest' ]
        steps:
        - uses: actions/checkout@v3

        - name: Build
          run: go build -v main.go
          working-directory: devops/ci/projeto-go-testes-main

        - name: Verify Artifact
          run: ls -l devops/ci/projeto-go-testes-main/main

        - name: Upload a Build Artifact
          uses: actions/upload-artifact@v4.5.0
          with: 
              name: programa
              path: devops/ci/projeto-go-testes-main/main
              
    docker:
        needs: build
        uses: .github/workflows/Docker.yml@${{ github.ref_name }}
        secrets: inherit
